/**
 * Remoteme rest for advanced integration
 * If You want i can hide it but there is nothing danger
 *
 * OpenAPI spec version: 1.0
 * Contact: contact@remoteme.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.remoteme.client.api;

import org.remoteme.client.invoker.ApiException;
import org.remoteme.client.invoker.ApiInvoker;
import org.remoteme.client.invoker.Pair;

import org.remoteme.client.model.*;

import java.util.*;

import org.remoteme.client.model.StandardResponse;

import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.Map;
import java.util.HashMap;
import java.io.File;

public class ArliterestpartnerApi {
  String basePath = "https://127.0.0.1:8082";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
   * createUser
   * 
   * @param userName someUser
   * @param email email
   * @param md5Password md5Password
   * @param partnerSecretToken contact to get one
   * @param aRLiteToken generated token
   * @return StandardResponse
   */
  public StandardResponse  createUser (String userName, String email, String md5Password, String partnerSecretToken, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'userName' is set
    if (userName == null) {
       throw new ApiException(400, "Missing the required parameter 'userName' when calling createUser");
    }
    // verify the required parameter 'email' is set
    if (email == null) {
       throw new ApiException(400, "Missing the required parameter 'email' when calling createUser");
    }
    // verify the required parameter 'md5Password' is set
    if (md5Password == null) {
       throw new ApiException(400, "Missing the required parameter 'md5Password' when calling createUser");
    }
    // verify the required parameter 'partnerSecretToken' is set
    if (partnerSecretToken == null) {
       throw new ApiException(400, "Missing the required parameter 'partnerSecretToken' when calling createUser");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/PARTNER_AUTH/createUser/{userName}/{email}/{md5Password}/{partnerSecretToken}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "userName" + "\\}", apiInvoker.escapeString(userName.toString())).replaceAll("\\{" + "email" + "\\}", apiInvoker.escapeString(email.toString())).replaceAll("\\{" + "md5Password" + "\\}", apiInvoker.escapeString(md5Password.toString())).replaceAll("\\{" + "partnerSecretToken" + "\\}", apiInvoker.escapeString(partnerSecretToken.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (StandardResponse) ApiInvoker.deserialize(localVarResponse, "", StandardResponse.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * createUser
   * 
   * @param userName someUser
   * @param md5Password md5Password
   * @param partnerSecretToken contact to get one
   * @param aRLiteToken generated token
   * @return StandardResponse
   */
  public StandardResponse  createUser1 (String userName, String md5Password, String partnerSecretToken, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'userName' is set
    if (userName == null) {
       throw new ApiException(400, "Missing the required parameter 'userName' when calling createUser1");
    }
    // verify the required parameter 'md5Password' is set
    if (md5Password == null) {
       throw new ApiException(400, "Missing the required parameter 'md5Password' when calling createUser1");
    }
    // verify the required parameter 'partnerSecretToken' is set
    if (partnerSecretToken == null) {
       throw new ApiException(400, "Missing the required parameter 'partnerSecretToken' when calling createUser1");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/PARTNER_AUTH/createUser/{userName}/{md5Password}/{partnerSecretToken}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "userName" + "\\}", apiInvoker.escapeString(userName.toString())).replaceAll("\\{" + "md5Password" + "\\}", apiInvoker.escapeString(md5Password.toString())).replaceAll("\\{" + "partnerSecretToken" + "\\}", apiInvoker.escapeString(partnerSecretToken.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (StandardResponse) ApiInvoker.deserialize(localVarResponse, "", StandardResponse.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * sayHi
   * say Hi
   * @param name name
   * @param partnerSecretToken partnerSecretToken
   * @param aRLiteToken generated token
   * @return String
   */
  public String  sayHi (String name, String partnerSecretToken, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'name' is set
    if (name == null) {
       throw new ApiException(400, "Missing the required parameter 'name' when calling sayHi");
    }
    // verify the required parameter 'partnerSecretToken' is set
    if (partnerSecretToken == null) {
       throw new ApiException(400, "Missing the required parameter 'partnerSecretToken' when calling sayHi");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/PARTNER_AUTH/sayHi/{name}/{partnerSecretToken}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "name" + "\\}", apiInvoker.escapeString(name.toString())).replaceAll("\\{" + "partnerSecretToken" + "\\}", apiInvoker.escapeString(partnerSecretToken.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * sayHiWithOptional
   * say Hi with optional
   * @param name 
   * @param partnerSecretToken contact to get one
   * @param aRLiteToken generated token
   * @return String
   */
  public String  sayHi1 (String name, String partnerSecretToken, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'name' is set
    if (name == null) {
       throw new ApiException(400, "Missing the required parameter 'name' when calling sayHi1");
    }
    // verify the required parameter 'partnerSecretToken' is set
    if (partnerSecretToken == null) {
       throw new ApiException(400, "Missing the required parameter 'partnerSecretToken' when calling sayHi1");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/PARTNER_AUTH/sayHiWithOptional/{name}/{partnerSecretToken}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "name" + "\\}", apiInvoker.escapeString(name.toString())).replaceAll("\\{" + "partnerSecretToken" + "\\}", apiInvoker.escapeString(partnerSecretToken.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * sayHiWithOptional
   * say Hi with optional
   * @param name 
   * @param surname surname
   * @param partnerSecretToken contact to get one
   * @param aRLiteToken generated token
   * @return String
   */
  public String  sayHi2 (String name, String surname, String partnerSecretToken, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'name' is set
    if (name == null) {
       throw new ApiException(400, "Missing the required parameter 'name' when calling sayHi2");
    }
    // verify the required parameter 'surname' is set
    if (surname == null) {
       throw new ApiException(400, "Missing the required parameter 'surname' when calling sayHi2");
    }
    // verify the required parameter 'partnerSecretToken' is set
    if (partnerSecretToken == null) {
       throw new ApiException(400, "Missing the required parameter 'partnerSecretToken' when calling sayHi2");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/PARTNER_AUTH/sayHiWithOptional/{name}/{surname}/{partnerSecretToken}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "name" + "\\}", apiInvoker.escapeString(name.toString())).replaceAll("\\{" + "surname" + "\\}", apiInvoker.escapeString(surname.toString())).replaceAll("\\{" + "partnerSecretToken" + "\\}", apiInvoker.escapeString(partnerSecretToken.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
}
