/**
 * Remoteme rest for advanced integration
 * If You want i can hide it but there is nothing danger
 *
 * OpenAPI spec version: 1.0
 * Contact: contact@remoteme.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.remoteme.client.api;

import org.remoteme.client.invoker.ApiException;
import org.remoteme.client.invoker.ApiInvoker;
import org.remoteme.client.invoker.Pair;

import org.remoteme.client.model.*;

import java.util.*;

import org.remoteme.client.model.VariableDto;
import org.remoteme.client.model.VariableSchedulerDto;
import org.remoteme.client.model.VariableSchedulerEntityDto;

import org.apache.http.entity.mime.MultipartEntityBuilder;

import java.util.Map;
import java.util.HashMap;
import java.io.File;

public class ArliterestvariablesApi {
  String basePath = "https://127.0.0.1:8082";
  ApiInvoker apiInvoker = ApiInvoker.getInstance();

  public void addHeader(String key, String value) {
    getInvoker().addDefaultHeader(key, value);
  }

  public ApiInvoker getInvoker() {
    return apiInvoker;
  }

  public void setBasePath(String basePath) {
    this.basePath = basePath;
  }

  public String getBasePath() {
    return basePath;
  }

  /**
   * add new Scheduler
   * add new VariableScheduler id is ignored
   * @param variableSchedulerDto variableSchedulerDto
   * @param variableName Variable name
   * @param variableType Variable type
   * @param aRLiteToken generated token
   * @return VariableSchedulerDto
   */
  public VariableSchedulerDto  addScheduler (VariableSchedulerDto variableSchedulerDto, String variableName, String variableType, String aRLiteToken) throws ApiException {
    Object localVarPostBody = variableSchedulerDto;
    // verify the required parameter 'variableSchedulerDto' is set
    if (variableSchedulerDto == null) {
       throw new ApiException(400, "Missing the required parameter 'variableSchedulerDto' when calling addScheduler");
    }
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
       throw new ApiException(400, "Missing the required parameter 'variableName' when calling addScheduler");
    }
    // verify the required parameter 'variableType' is set
    if (variableType == null) {
       throw new ApiException(400, "Missing the required parameter 'variableType' when calling addScheduler");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/{variableName}/{variableType}/schedulers/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "variableName" + "\\}", apiInvoker.escapeString(variableName.toString())).replaceAll("\\{" + "variableType" + "\\}", apiInvoker.escapeString(variableType.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (VariableSchedulerDto) ApiInvoker.deserialize(localVarResponse, "", VariableSchedulerDto.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * add variables
   * return enw created variable, mode is set as local
   * @param v v
   * @param aRLiteToken generated token
   * @return VariableDto
   */
  public VariableDto  createVariable (VariableDto v, String aRLiteToken) throws ApiException {
    Object localVarPostBody = v;
    // verify the required parameter 'v' is set
    if (v == null) {
       throw new ApiException(400, "Missing the required parameter 'v' when calling createVariable");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (VariableDto) ApiInvoker.deserialize(localVarResponse, "", VariableDto.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * add new Scheduler
   * update VariableScheduler
   * @param schedulerId schedulerId
   * @param aRLiteToken generated token
   * @return Object
   */
  public Object  deleteScheduler (Integer schedulerId, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'schedulerId' is set
    if (schedulerId == null) {
       throw new ApiException(400, "Missing the required parameter 'schedulerId' when calling deleteScheduler");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/schedulers/{schedulerId}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "schedulerId" + "\\}", apiInvoker.escapeString(schedulerId.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (Object) ApiInvoker.deserialize(localVarResponse, "", Object.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * delete variable
   * return rmeoved variable
   * @param variableName variableName
   * @param variableType variableType
   * @param aRLiteToken generated token
   * @return VariableDto
   */
  public VariableDto  deleteVariable (String variableName, String variableType, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
       throw new ApiException(400, "Missing the required parameter 'variableName' when calling deleteVariable");
    }
    // verify the required parameter 'variableType' is set
    if (variableType == null) {
       throw new ApiException(400, "Missing the required parameter 'variableType' when calling deleteVariable");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/{variableName}/{variableType}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "variableName" + "\\}", apiInvoker.escapeString(variableName.toString())).replaceAll("\\{" + "variableType" + "\\}", apiInvoker.escapeString(variableType.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (VariableDto) ApiInvoker.deserialize(localVarResponse, "", VariableDto.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * get schedulers for variable
   * Get schedulers for variable
   * @param variableName Variable name
   * @param variableType Variable type
   * @param aRLiteToken generated token
   * @return List<VariableSchedulerEntityDto>
   */
  public List<VariableSchedulerEntityDto>  getSchedulers (String variableName, String variableType, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
       throw new ApiException(400, "Missing the required parameter 'variableName' when calling getSchedulers");
    }
    // verify the required parameter 'variableType' is set
    if (variableType == null) {
       throw new ApiException(400, "Missing the required parameter 'variableType' when calling getSchedulers");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/{variableName}/{variableType}/schedulers/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "variableName" + "\\}", apiInvoker.escapeString(variableName.toString())).replaceAll("\\{" + "variableType" + "\\}", apiInvoker.escapeString(variableType.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (List<VariableSchedulerEntityDto>) ApiInvoker.deserialize(localVarResponse, "array", VariableSchedulerEntityDto.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * get Variables text format value 
   * 
   * @param name name
   * @param type type
   * @param aRLiteToken generated token
   * @return String
   */
  public String  getVariableTextValue (String name, String type, String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;
    // verify the required parameter 'name' is set
    if (name == null) {
       throw new ApiException(400, "Missing the required parameter 'name' when calling getVariableTextValue");
    }
    // verify the required parameter 'type' is set
    if (type == null) {
       throw new ApiException(400, "Missing the required parameter 'type' when calling getVariableTextValue");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/getVariableTextValue/{name}/{type}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "name" + "\\}", apiInvoker.escapeString(name.toString())).replaceAll("\\{" + "type" + "\\}", apiInvoker.escapeString(type.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (String) ApiInvoker.deserialize(localVarResponse, "", String.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * getVariables
   * 
   * @param aRLiteToken generated token
   * @return List<VariableDto>
   */
  public List<VariableDto>  getVariables (String aRLiteToken) throws ApiException {
    Object localVarPostBody = null;

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/".replaceAll("\\{format\\}","json");

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (List<VariableDto>) ApiInvoker.deserialize(localVarResponse, "array", VariableDto.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * set Variable value using string format
   * 
   * @param value value
   * @param name name
   * @param type type
   * @param aRLiteToken generated token
   * @return void
   */
  public void  setVariableTextValue (String value, String name, String type, String aRLiteToken) throws ApiException {
    Object localVarPostBody = value;
    // verify the required parameter 'value' is set
    if (value == null) {
       throw new ApiException(400, "Missing the required parameter 'value' when calling setVariableTextValue");
    }
    // verify the required parameter 'name' is set
    if (name == null) {
       throw new ApiException(400, "Missing the required parameter 'name' when calling setVariableTextValue");
    }
    // verify the required parameter 'type' is set
    if (type == null) {
       throw new ApiException(400, "Missing the required parameter 'type' when calling setVariableTextValue");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/setVariableTextValue/{name}/{type}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "name" + "\\}", apiInvoker.escapeString(name.toString())).replaceAll("\\{" + "type" + "\\}", apiInvoker.escapeString(type.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return ;
      }
      else {
        return ;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * updateScheduler
   * 
   * @param variableSchedulerDto variableSchedulerDto
   * @param schedulerId schedulerId
   * @param aRLiteToken generated token
   * @return Object
   */
  public Object  updateScheduler (VariableSchedulerDto variableSchedulerDto, Integer schedulerId, String aRLiteToken) throws ApiException {
    Object localVarPostBody = variableSchedulerDto;
    // verify the required parameter 'variableSchedulerDto' is set
    if (variableSchedulerDto == null) {
       throw new ApiException(400, "Missing the required parameter 'variableSchedulerDto' when calling updateScheduler");
    }
    // verify the required parameter 'schedulerId' is set
    if (schedulerId == null) {
       throw new ApiException(400, "Missing the required parameter 'schedulerId' when calling updateScheduler");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/schedulers/{schedulerId}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "schedulerId" + "\\}", apiInvoker.escapeString(schedulerId.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (Object) ApiInvoker.deserialize(localVarResponse, "", Object.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
  /**
   * update variable name and/or properties
   * it find variable by given name and type and updated based on variableDto - ot does not update type!
   * @param variableDto variableDto
   * @param variableName variableName
   * @param variableType variableType
   * @param aRLiteToken generated token
   * @return VariableDto
   */
  public VariableDto  updateVariable (VariableDto variableDto, String variableName, String variableType, String aRLiteToken) throws ApiException {
    Object localVarPostBody = variableDto;
    // verify the required parameter 'variableDto' is set
    if (variableDto == null) {
       throw new ApiException(400, "Missing the required parameter 'variableDto' when calling updateVariable");
    }
    // verify the required parameter 'variableName' is set
    if (variableName == null) {
       throw new ApiException(400, "Missing the required parameter 'variableName' when calling updateVariable");
    }
    // verify the required parameter 'variableType' is set
    if (variableType == null) {
       throw new ApiException(400, "Missing the required parameter 'variableType' when calling updateVariable");
    }

    // create path and map variables
    String localVarPath = "/arLite/rest/v1/variables/{variableName}/{variableType}/".replaceAll("\\{format\\}","json").replaceAll("\\{" + "variableName" + "\\}", apiInvoker.escapeString(variableName.toString())).replaceAll("\\{" + "variableType" + "\\}", apiInvoker.escapeString(variableType.toString()));

    // query params
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    // header params
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    // form params
    Map<String, String> localVarFormParams = new HashMap<String, String>();


    localVarHeaderParams.put("ARLiteToken", ApiInvoker.parameterToString(aRLiteToken));

    String[] localVarContentTypes = {
      "application/json"
    };
    String localVarContentType = localVarContentTypes.length > 0 ? localVarContentTypes[0] : "application/json";

    if (localVarContentType.startsWith("multipart/form-data")) {
      // file uploading
      MultipartEntityBuilder localVarBuilder = MultipartEntityBuilder.create();
      

      localVarPostBody = localVarBuilder.build();
    } else {
      // normal form params
          }

    try {
      String localVarResponse = apiInvoker.invokeAPI(basePath, localVarPath, "PUT", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarContentType);
      if(localVarResponse != null){
        return (VariableDto) ApiInvoker.deserialize(localVarResponse, "", VariableDto.class);
      }
      else {
        return null;
      }
    } catch (ApiException ex) {
      throw ex;
    }
  }
}
